spring:
  influxdb:
    url: http://localhost:8086/
    database: boot
    username: admin
    password: secret
    retention-policy: autogen

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      influx:
        uri: http://localhost:8086
        db: boot
        enabled: true  # export to InfluxDB enable
        step: 10s
        user-name: admin
        password: secret
      prometheus:
        enabled: true  # prometheus enable
    tags:
      application: secuwifi
